# Generated by Django 5.0.2 on 2024-02-23 03:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmd_web', '0002_remove_post_created_at_post_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
