# Generated by Django 5.0.2 on 2024-02-23 04:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmd_web', '0003_alter_person_joined_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='joined_date',
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='joined_date',
            field=models.DateField(null=True),
        ),
    ]
